# Generated by Django 3.2.25 on 2024-11-28 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answers', models.IntegerField()),
                ('wrong_answers', models.IntegerField()),
                ('points', models.IntegerField(default=0)),
                ('number_of_exercises', models.IntegerField(default=0)),
                ('count_seconds', models.DurationField()),
                ('average_answer_time', models.DurationField()),
                ('total_time', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
