# Generated by Django 3.2.25 on 2024-11-29 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20241129_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
