# Generated by Django 3.2.25 on 2024-12-01 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_data_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('wrong_answers', models.IntegerField(default=0)),
                ('total_time', models.IntegerField(default=0)),
                ('chord_sounds', models.FileField(upload_to='chords/')),
                ('chord_type', models.CharField(choices=[('major', 'Major'), ('minor', 'Minor'), ('sus2', 'Sus2'), ('sus4', 'Sus4'), ('diminished', 'Diminished')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Intervals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('wrong_answers', models.IntegerField(default=0)),
                ('total_time', models.IntegerField(default=0)),
                ('interval_sounds', models.FileField(upload_to='interval_sounds/')),
                ('interval_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('wrong_answers', models.IntegerField(default=0)),
                ('total_time', models.IntegerField(default=0)),
                ('note_sounds', models.FileField(upload_to='notes/')),
            ],
        ),
        migrations.CreateModel(
            name='Rhythm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('wrong_answers', models.IntegerField(default=0)),
                ('total_time', models.IntegerField(default=0)),
                ('rhythmic_sounds', models.FileField(upload_to='rhythms/')),
            ],
        ),
        migrations.CreateModel(
            name='Scales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('wrong_answers', models.IntegerField(default=0)),
                ('total_time', models.IntegerField(default=0)),
                ('scale_sounds', models.FileField(upload_to='scales/')),
            ],
        ),
        migrations.RemoveField(
            model_name='data',
            name='correct_answers',
        ),
        migrations.RemoveField(
            model_name='data',
            name='wrong_answers',
        ),
        migrations.AlterField(
            model_name='data',
            name='average_answer_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='data',
            name='count_seconds',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
