# Generated by Django 3.2.25 on 2024-12-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20241201_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='note_name',
            field=models.CharField(choices=[('C', 'C'), ('C#', 'C#'), ('D', 'D'), ('D#', 'D#'), ('E', 'E'), ('F', 'F'), ('F#', 'F#'), ('G', 'G'), ('G#', 'G#'), ('A', 'A'), ('A#', 'A#'), ('B', 'B')], default='C', max_length=20),
        ),
        migrations.AddField(
            model_name='scales',
            name='scale_type',
            field=models.CharField(choices=[('Minor Scale', 'Minor Scale'), ('Major Scale', 'Major Scale'), ('Harmonic Minor', 'Harmonic Minor'), ('Pentatonic', 'Pentatonic')], default='Major Scale', max_length=20),
        ),
        migrations.AlterField(
            model_name='chords',
            name='chord_type',
            field=models.CharField(choices=[('major', 'Major'), ('minor', 'Minor'), ('sus2', 'Sus2'), ('sus4', 'Sus4'), ('diminished', 'Diminished')], default='major', max_length=20),
        ),
        migrations.AlterField(
            model_name='intervals',
            name='interval_type',
            field=models.CharField(choices=[('minorsecond', 'Minor second'), ('minorthird', 'Minor third'), ('majorsecond', 'Major second'), ('perfectfourth', 'Perfect fourth'), ('perfectfifth', 'Perfect fifth'), ('octave', 'Octave')], default='minorsecond', max_length=20),
        ),
        migrations.AlterField(
            model_name='notes',
            name='note_sounds',
            field=models.FileField(upload_to='note_sounds/'),
        ),
        migrations.AlterField(
            model_name='scales',
            name='scale_sounds',
            field=models.FileField(upload_to='scale_sounds/'),
        ),
    ]
